name: MATLAB Tests

on: 
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  matlab:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: 'R2024a'  # Specify the MATLAB release you are using

      - name: Run MATLAB tests
        run: |
          matlab -batch "cd('tests'); results = runtests('SampleTests.m'); assert(all([results.Passed]), 'Some tests failed');"
