name: MATLAB Tests

on: [push, pull_request]

jobs:
  matlab:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: 'R2024a'  # Specify the MATLAB release you are using

      - name: Install MATLAB Toolboxes
        run: |
          matlab -batch "toolboxes = {'Statistics and Machine Learning Toolbox', 'Optimization Toolbox', 'Bioinformatics Toolbox'}; installedToolboxes = cellfun(@(x) x.Name, ver, 'UniformOutput', false); missingToolboxes = setdiff(toolboxes, installedToolboxes); if ~isempty(missingToolboxes), error('Missing toolboxes: %s', strjoin(missingToolboxes, ', ')); end"
          
      - name: Run MATLAB tests
        run: |
          matlab -batch "cd('tests'); results = runtests('SampleTests.m'); assert(all([results.Passed]), 'Some tests failed');"
